import streamlit as st
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# Import our custom modules
from core.mapping import mock_encode_and_project
from search import find_geodesic_neighbors

st.set_page_config(layout="wide", page_title="Poincaré HIS Triage", page_icon="🩺")

@st.cache_data
def load_data():
    # Load the CSV generated by the pipeline in Phase 1
    return pd.read_csv("data/full_dataset_manifold.csv")

def main():
    st.title("🩺 Poincaré HIS Triage Dashboard")
    st.markdown("""
    **Continuous Clinical Knowledge Base & Dynamic Thresholding Demo**  
    *This dashboard implements the real-time inference pipeline described in the paper.*
    """)
    
    df_kb = load_data()
    col1, col2 = st.columns([1, 2])
    
    with col1:
        st.header("1. Live Patient Input")
        with st.form("patient_input"):
            st.text_area("EHR Clinical Notes (ClinicalBERT input)", 
                         "Patient presents with shortness of breath, mild coughing, and chest pain. History of smoking.")
            st.file_uploader("Upload Chest Radiograph (ResNet input)", type=['png', 'jpg', 'dicom'])
            
            # Dynamic Thresholding Dial
            st.slider("Dynamic Recall Threshold (Sensitivity)", min_value=0.0, max_value=1.0, value=0.18, step=0.01,
                      help="Paper Contribution: Lower threshold for high-recall screening of Mass/Hernia.")
            
            submit_btn = st.form_submit_button("Run Hyperbolic Fusion")
            
    with col2:
        st.header("2. Continuous Manifold Projection")
        
        if submit_btn:
            with st.spinner("Mapping to Poincaré Ball ($\mathcal{P}^3$)..."):
                
                # 1. Map to Manifold using the core module
                query_coord = mock_encode_and_project("text", "image")
                query_radius = np.linalg.norm(query_coord)
                
                # 2. Geodesic Search using the search module
                neighbors = find_geodesic_neighbors(query_coord, df_kb, k=5)
                
                # Risk Stratification based on boundary proximity
                if query_radius > 0.7:
                    st.error(f"🚨 CRITICAL ALARM: Patient mapped to boundary (Severity Radius: {query_radius:.2f}). High risk of Mass/Hernia.")
                elif query_radius > 0.3:
                    st.warning(f"⚠️ MODERATE RISK: Patient mapped to intermediate zone (Severity Radius: {query_radius:.2f}).")
                else:
                    st.success(f"✅ LOW RISK: Patient mapped near origin (Severity Radius: {query_radius:.2f}).")
                
                st.subheader("Interactive Knowledge Base Topography")
                
                fig = px.scatter_3d(df_kb, x='poincare_x', y='poincare_y', z='poincare_z',
                                    color='primary_diagnosis', opacity=0.6, size_max=8,
                                    color_discrete_map={"Normal": "green", "Infiltration": "yellow", 
                                                        "Effusion": "orange", "Mass": "red", "Hernia": "darkred"})
                
                # Add the New Query Patient as a large marker
                fig.add_trace(go.Scatter3d(
                    x=[query_coord[0]], y=[query_coord[1]], z=[query_coord[2]],
                    mode='markers+text',
                    marker=dict(size=12, color='black', symbol='diamond'),
                    text=["NEW PATIENT"],
                    textposition="top center",
                    name="Query"
                ))
                
                # Draw the theoretical boundary (sphere shell outline)
                u = np.linspace(0, 2 * np.pi, 50)
                v = np.linspace(0, np.pi, 50)
                x = np.outer(np.cos(u), np.sin(v))
                y = np.outer(np.sin(u), np.sin(v))
                z = np.outer(np.ones(np.size(u)), np.cos(v))
                fig.add_trace(go.Surface(x=x, y=y, z=z, opacity=0.1, showscale=False, colorscale='Greys', name="P3 Boundary"))
                
                fig.update_layout(margin=dict(l=0, r=0, b=0, t=0), height=500)
                st.plotly_chart(fig, use_container_width=True)
                
                st.subheader("3. Retrieved Historical Precedents (Nearest $d_{\mathcal{P}}$)")
                st.dataframe(neighbors[['patient_id', 'primary_diagnosis', 'treatment_outcome', 'd_P_distance', 'severity_radius']], use_container_width=True)

        else:
            st.info("👈 Upload patient data and click 'Run Hyperbolic Fusion' to project the patient into the clinical knowledge base.")

if __name__ == "__main__":
    main()
